#!/usr/bin/env python
#coding: utf-8

import string
import xlrd
import requests
from bs4 import BeautifulSoup
import os
import time
from os.path import abspath
from random import*

import sys
from xlwt import Workbook
import urllib2
import re
from itertools import islice
import bs4 as bs
import operator
import HTMLParser
locations = ['AF', 'EU', 'ME', 'NA%3AUS']

file1 = '/home/tuf20858/analchallenge/temp.txt'

file2 = '/home/tuf20858/analchallenge/temp2.txt'


def stripNonAlphaNum(text):
    import re
    return re.compile(r'\W+', re.UNICODE).split(text)

# loop thru list
def graburls():
#connect to a UR

    i = 0
    while i < 4:
        link = 'https://clinicaltrials.gov/ct2/results/map?term=Lysosomal+Storage+Disorders&map=' + locations[i]
        website = urllib2.urlopen(link).read()
        soup = bs.BeautifulSoup(website, 'lxml')
        body = soup.body
        for record in body.findAll('tr'):
            for data in record.findAll('td'):
                a =(data.text)

                s = stripNonAlphaNum(a)
                for line in s:
                    s=(line.replace('u', '').replace(',','').replace('[', '').replace(' ', '').replace("'", '').replace('],]','').replace(']', ''))
                    print s

        i = i +1



graburls()
